### ISSUE TITLE
SSIM

### ISSUE THREAD

**Issue by EKChloe** [INVOKERer/DeepRFT#14]
When you test SSIM ，did you use the function from skimage.metrics import structural_similarity？And set
structural_similarity(p_numpy, label_numpy, data_range=1，multichannel=True)

**Comment by INVOKERer** [comment]
No, the test code for PSNR and SSIM is from [MPRNet](https://github.com/swz30/MPRNet/tree/main/Deblurring). SSIM may be different is you directly use  skimage.metrics.structural_similarity.

**Comment by EKChloe** [comment]
but which one is correct？Results calculated by MPRNet that way or skimage.metrics.structural_similarity？Or just choose the highest way as experiment result

**Comment by INVOKERer** [comment]
We use the results calculated by the code from MPRNet.

**Comment by EKChloe** [comment]
Ok，thank you for your reply
