### ISSUE TITLE
about the gopro dataset

### ISSUE THREAD

**Issue by dawnlh** [INVOKERer/DeepRFT#46]
The gopro dataset provides two kinds of blurry images, i.e., 'blur' & 'blur_gamma'. And the original paper use 'blur_gamma' for experiments. But in your paper, it seems that you use the 'blur' dataset. I wonder if you have noticed this issue? And are all the competing methods  trained on 'blur'?

**Comment by INVOKERer** [comment]
We use the "blur" version of the GoPro dataset following [MPRNet.](https://github.com/swz30/MPRNet/tree/main/Deblurring/Datasets). All the competing methods were trained on the same dataset.

**Comment by dawnlh** [comment]
Got it! Thanks for your prompt reply.
