### ISSUE TITLE
关于测试和验证的一个小问题

### ISSUE THREAD

**Issue by Redamancy0222** [INVOKERer/DeepRFT#57]
您好，看到您在之前的回答说过您的模型使用patch的测试方法，想问一下这块内容具体是代码中的哪部分呢？是在image_restoration_model.py里面def nondist_validation(self, dataloader, current_iter, tb_logger, save_img, rgb2bgr, use_image)这段代码里实现的吗？还有就是我看test的window_size参数设置为8，这个具体是指哪个大小呢？我理解的滑动测试是指在测试图片上顺序选取256*256的图像块输入网络测试，这个尺寸和训练一致，最后将复原结果整合拼接一下，这里的8是指滑动步长吗？不知道我理解的是否有误，期待您的回复和答疑。感谢~~

**Comment by INVOKERer** [comment]
image_restoration_model.py里的window_size参数应该是原本框架自带的，滑动测试的具体参数为yml中的train_size和overlap_size。
