### ISSUE TITLE
Fast Fourier convolutions

### ISSUE THREAD

**Issue by imageCompression1995** [INVOKERer/DeepRFT#6]
Thanks for the good sharing. I concern about the ablation study on FFC (in Table 7). Did you directly replace the FT branch with FFC[41], which uses the BN operation (harmful to deblurring) ?

**Comment by INVOKERer** [comment]
FFC[41] was used as a ResBlock, just like it was used in its ori paper.

**Comment by imageCompression1995** [comment]
Ok, thanks. By the way, is FFC with the BN operation?

**Comment by INVOKERer** [comment]
Yes, BN is kept in FFC.

**Comment by imageCompression1995** [comment]
Ok, thanks.
