### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by cslvjt** [INVOKERer/DeepRFT#62]
作者您好，感谢你们优秀的工作。我在使用你们原本的代码进行测试时发现，对整图推理时的PSNR性能较低，请问你们是否有这样的情况。谢谢

**Comment by INVOKERer** [comment]
我不知道您所说的性能下降是怎么样的下降？是与文章报的指标有差别么？如果是没有切patch直接整图测试，会存在性能下降问题。如果是切patch，可以尝试v2版本。

**Comment by cslvjt** [comment]
好的，我的意思就是，在GoPro数据集上整图推理的PSNR值相比与您论文中的值低。我这边用您提供的方法再次测量一下，谢谢回复。

**Comment by INVOKERer** [comment]
您好，我这边重新测了下v1的代码发现确实存在问题，我没能找出问题出在哪里。v2版本应该不存在这个问题。。。
