### ISSUE TITLE
Complete training loss curve

### ISSUE THREAD

**Issue by suiyizhao** [INVOKERer/DeepRFT#8]
Thanks for your wonderful deblurring work.
I noticed that the provided loss curve in paper is only 120, and the epoch settting is 3000. 
Could you  provide a complete training loss curve and complete performance curve on GoPro test dataset?
Thank you.

**Comment by INVOKERer** [comment]
Sorry, we only saved the first 120 epoch loss data when we did this experiment. From what I've observed, all the subsequent loss curve would not fluctuate wildly.
